name = "SwapSort"
uuid = "518c31a9-72dd-41b9-826f-606c4258a582"
version = "1.3.0"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Unroll = "36e64239-2ab9-4580-84fb-56737a503d36"

[compat]
Aqua = "0.8"
JSON = "0.21, 1"
Random = "1"
Scanf = "0.5"
Test = "1"
Unroll = "0.1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Scanf = "6ef1bc8b-493b-44e1-8d40-549aa65c4b41"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Random", "Test"]
